# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='id',
        ),
        migrations.AddField(
            model_name='cruise',
            name='code_to_cruise_id',
            field=models.CharField(default=None, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
