# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0002_auto_20170325_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='nights',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='sail_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='sail_nights',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
