# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0002_auto_20170325_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='code_to_cruise_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
