# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0003_auto_20170325_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='cruise_id',
        ),
    ]
