# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0004_auto_20170325_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='adults',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
