# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0005_auto_20170325_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabingrade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cabingrade',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cabingrade',
            name='position_forward',
        ),
        migrations.RemoveField(
            model_name='cabingrade',
            name='position_middle',
        ),
        migrations.RemoveField(
            model_name='cabingrade',
            name='position_rear',
        ),
    ]
