# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0006_auto_20170325_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='slug',
            field=models.URLField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
    ]
