# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0006_auto_20170325_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabingrade',
            name='colour_code',
        ),
    ]
