# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0007_auto_20170325_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cruise',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='sail_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='sail_nights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
